# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TarunPatel
email: tarun.h.patel@student.uts.edu.au
description: >-
  I am a passionate and systems-focused software engineering student with a strong foundation in low-level C programming and embedded systems. I have developed real-time microcontroller projects using AVR C and am currently building STL-style containers in C++ to understand memory management and iterator design. I thrive in environments where I can work at the hardware-software boundary and am excited to grow into a Linux kernel engineering role. I aim to contribute to open-source systems like Ubuntu while developing deep kernel expertise within a globally distributed team.

baseurl: ""
url: https://TarunPatel03.github.io
github_username: TarunPatel03

author:
  avatar: ""
  name: "Tarun Patel"
  bio: "Software Engineering student focused on embedded systems and programming."
  location: "Sydney"
  employer: "University of Technology Sydney"
  github: "TarunPatel03"
  linkedin: ""

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
  pages:
    output: true
    permalink: /:title/

defaults: []
permalink: pretty

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
